### PR TITLE
[DOC-43] [DOC-34] Ens updates

### PR DESCRIPTION
**Pull request by awmuncy**
Add ENS command details to docs, and split CLI command out into separate pages.

### CODE REVIEW

**Comment by dtbuchholz** [comment]
@awmuncy I added a bunch of changes here if you'd like to approve/merge into yours: https://github.com/tablelandnetwork/docs/pull/123

I had some legacy things I never cleaned up in the docs migration and figured I'd just knock it out here.

**Comment by awmuncy** [comment]
> @awmuncy I added a bunch of changes here if you'd like to approve/merge into yours: #123
> 
> I had some legacy things I never cleaned up in the docs migration and figured I'd just knock it out here.

Beautiful, merged it in. Also, my PR is to main. Should it be to staging? I know docs has a different flow than other repos.

**Comment by dtbuchholz** [comment]
@awmuncy I think moving forward, yes, this can just go to main. I do have a lot in staging right now that I'd like to merge, so maybe do staging for now? But, I think staging will have some small conflicts with anything in yours that mentions ETH Goerli/Sepolia.

**Comment by awmuncy** [comment]
> @awmuncy I think moving forward, yes, this can just go to main. I do have a lot in staging right now that I'd like to merge, so maybe do staging for now? But, I think staging will have some small conflicts with anything in yours that mentions ETH Goerli/Sepolia.

Okay, I pointed to staging and resolved the conflicts. You can give it another look now to make sure it looks like you expected in the sidebar.

**Review by dtbuchholz — APPROVED** [review]
cool, lgtm!

**Pull request merged**
