### PR TITLE
fix: typos in github links in repos.md

### PR DESCRIPTION
**Pull request by dimitrov-d**

### CODE REVIEW

**Comment by joewagner** [comment]
@dimitrov-d This is great!  Thank you for the submission.

**Review by dtbuchholz — APPROVED** [review]
These look great @dimitrov-d, thanks for doing this!

**Comment by dtbuchholz** [comment]
@dimitrov-d it looks like this merge is getting blocked due to the unsigned commit. Could you try [signing the commit](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) like `git commit -S …` after setting up a GPG key?

**Comment by dimitrov-d** [comment]
> @dimitrov-d it looks like this merge is getting blocked due to the unsigned commit. Could you try [signing the commit](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) like `git commit -S …` after setting up a GPG key?

Done! I've overwritten my previous commit with a signed one.

**Review by dtbuchholz — APPROVED** [review]

**Comment by dtbuchholz** [comment]
thanks @dimitrov-d—feel free to merge (i can't recall what you're allowed to merge on this repo—if not, i can do it!)

**Comment by dimitrov-d** [comment]
> thanks @dimitrov-d—feel free to merge (i can't recall what you're allowed to merge on this repo—if not, i can do it!)

I do not have merge access, you can have the pleasure :)

**Pull request merged**
