### PR TITLE
[DOC-7] Make docs for FEVM support live

### PR DESCRIPTION
**Pull request by awmuncy**
This PR adds a link to the Filecoin page in the sidebar of the documentation site, making it easier for developers to find information on using Filecoin with Tableland. No changes were made to the existing Filecoin page.

This PR should be merged when the Filecoin support is announced.

### CODE REVIEW

**Review by dtbuchholz — APPROVED** [review]
🤝

**Comment by dtbuchholz** [comment]
@awmuncy with my staging branch deletion / recreation, this got auto closed. Related thought—should we just make this live but comment out the mainnet FVM part of the chains docs?

**Comment by awmuncy** [comment]
> @awmuncy with my staging branch deletion / recreation, this got auto closed. Related thought—should we just make this live but comment out the mainnet FVM part of the chains docs?

Good point! I've done that, we can merge this whenever.

**Review by dtbuchholz — APPROVED** [review]
Cool, works for me

**Comment by dtbuchholz** [comment]
@awmuncy can i get a 👍? added a small callout about block / SQL finality, before i merge this.

**Review by dtbuchholz — APPROVED** [review]
Oh, lol yeah, missed that 🤘

**Pull request merged**
